# Generated by Django 5.1.6 on 2025-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titleIt', models.CharField(default='Default title in Italian', max_length=255)),
                ('contentIt', models.TextField(default='Default content in Italian')),
                ('short_descriptionIt', models.CharField(default='Default short in Italian', max_length=1000)),
                ('titleEn', models.CharField(default='Default title in English', max_length=255)),
                ('contentEn', models.TextField(default='Default content in English')),
                ('short_descriptionEn', models.CharField(default='Default short in English', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('tech_list', models.JSONField(default=list)),
            ],
        ),
    ]
