# Generated by Django 5.1.6 on 2025-03-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_project_short_descriptionen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTxts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text_it', models.TextField(default='Default about text in Italian')),
                ('about_text_en', models.TextField(default='Default about text in English')),
                ('about_text_es', models.TextField(default='Default about text in Spanish')),
                ('tech_text_it', models.TextField(default='Default tech text in Italian')),
                ('tech_text_en', models.TextField(default='Default tech text in English')),
                ('tech_text_es', models.TextField(default='Default tech text in Spanish')),
                ('partners_text_it', models.TextField(default='Default partners text in Italian')),
                ('partners_text_en', models.TextField(default='Default partners text in English')),
                ('partners_text_es', models.TextField(default='Default partners text in Spanish')),
            ],
        ),
    ]
