# Generated by Django 5.1.6 on 2025-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_homepagetxts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
